theme: jekyll-theme-midnight
title:  '"Drop that stereo before I blow your goddamn nuts off, asshole."'
author: txtack
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I started this as a learning lab tutorial in GitHub.
  Here we are now, what a train wreck.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  txtack # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
